if(NOT DEFINED CMAKE_OCaml_COMPILE_OBJECT)
    set(CMAKE_OCaml_COMPILE_OBJECT "<CMAKE_OCaml_COMPILER> -o <OBJECT> -c <SOURCE>")
endif()

if(NOT DEFINED CMAKE_OCaml_LINK_EXECUTABLE)
    set(CMAKE_OCaml_LINK_EXECUTABLE "<CMAKE_OCaml_COMPILER> -o <TARGET> <OBJECTS>")
endif()
set(CMAKE_OCaml_OUTPUT_EXTENSION_REPLACE 1)
set(CMAKE_OCaml_INFORMATION_LOADED 1)